#/var/lib/tomcat8/webapps/ROOT

version: 0.0
os: linux
files:
  - source: source
    destination: /var/lib/tomcat8/webapps/ROOT
hooks:
  BeforeInstall:
    - location: aws/check.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws/check.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws/restart.sh
      timeout: 300
      runas: root
